name: hbm-local

services:

  frontend.webui:
    container_name: frontend.webui
    image: home-budget-manager/frontend.webui:local
    restart: always
    volumes:
      - ./frontend.webui/configuration.json:/app/public/configuration.json

  bff.webui:
    container_name: bff.webui
    image: home-budget-manager/bff.webui:local
    restart: always
    environment:
      - DomainServices__Services__0__url=http://services.accounts:8080

  services.accounts:
    container_name: services.accounts
    image: home-budget-manager/services.accounts:local
    restart: always

  reverse-proxy:
    container_name: reverse-proxy
    image: nginx:latest
    restart: always
    ports:
      - "6001:80"
    volumes:
      - ./nginx/hbm.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend.webui
      - bff.webui
